Add offer
SuperProjects2a/musingo-frontend pull request #4
Opened 2022-04-01 14:36 UTC by MMaciek17

walidacja + fix
// box na razie zostawiam

2022-04-02 13:08 UTC, MMaciek17 reviewed
navbar fix

2022-04-03 15:19 UTC, Karolina999 requested changes
- zmienić placeholder w tytule (to strona muzyczna, nikt nie będzie sprzedawał telefonu :P)
- nie da się wpisać ceny
- po wciśnięciu przycisku dodaj ogłoszenie powinno nie przejść i pokazać wszystkie nieuzupełnione pola (pokazuje tylko na cenę - jak jest wpisana to działa poprawnie)
- dodać do karty margines od góry i dołu od sm

2022-04-03 20:26 UTC, Karolina999 requested changes
- Nie można wpisać ceny 1-9, można wpisać np. 01
- Walidacja - wprowadzić spójność ("To pole nie może zostać puste" lub "To pole jest wymagane")

2022-04-04 11:13 UTC, Karolina999 approved these changes
lgtm

2022-04-04 11:14 UTC, merged